config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  root "articles#index"
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "signup" => "users#new"

  post "users/create" => "users#create"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  get "users/index" => "users#index"
  post "users/:id/destroy" => "users#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, 
    presence: true,
    length: { minimum: 5 }
end

app/models/like.rb
class Like < ApplicationRecord
    validates :user_id, {presence: true}
    validates :post_id, {presence: true}
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, {presence: true, length: {maximum: 140}}
    # user_idカラムにバリデーションを追加してください
    validates :user_id, {presence: true}
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
  
    validates :name, {presence: true}
    validates :password, {presence: true}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
  
    def set_current_user
      @current_user = User.find_by(id: session[:user_id])
    end
    
    
   def authenticate_user
   if @current_user == nil
     flash[:notice] = "ログインが必要です"
     redirect_to("/login")
   end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to articles_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 

 before_action:authenticate_user
 def index
    @articles = Article.all
 end

 # 記事の表示
 def show
    @article = Article.find(params[:id])
 end

 # 記事の作成
 def new 
    @article = Article.new
 end

 # 記事の登録
 def create
     # articleモデルの属性の初期化
     @article = Article.new(article_params)

     # DBに登録できた場合
     if @article.save
      flash[:notice] = "投稿を作成しました"
        # 記事ページに遷移する
        redirect_to articles_path
    # DBに登録できなかった場合
    else
        # 作成ページに遷移する
        render 'new'
    end
 end

 # 記事の編集
 def edit
    @article = Article.find(params[:id])
 end

 # 記事の更新
 def update
    @article = Article.find(params[:id])
   # DBに登録できた場合
   if @article.update(article_params)
    # 記事ページに遷移する
    redirect_to articles_path
# DBに登録できなかった場合
else
    # 編集ページに遷移する
    render 'edit'
end
 end

 # 記事の削除
 def destroy
    @article = Article.find(params[:id])

        # 記事の削除
        @article.destroy
       
        # TOPページに遷移する
        redirect_to articles_path
 end

  # showアクションにリダイレクト
 private
 def article_params
     params.require(:article).permit(:title, :text)
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    before_action :forbid_login_user, {only: [:top]}

    def top
    end
    
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}
  
    def index
        @users = User.all
      end
      
      def show
        @user = User.find_by(id: params[:id])
      end
    
    def new
     @user = User.new

    end

    def create
    @user = User.new(name: params[:name], password: params[:password])
    if @user.save
        session[:user_id] = @user.id

        flash[:notice] = "登録が完了しました"
        
    redirect_to articles_path
    else
        render("users/new")
    end
    end


    def login
       @user =  User.find_by(name: params[:name])
       if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:notice] = "ログインしました！"
        redirect_to articles_path
       else
        @error_message = "メールアドレスまたはパスワードが間違っています"
        @name = params[:name]
        @password = params[:password]
        render ("users/login_form")
       end
    end

    def login_form
    end

    def logout
        session[:user_id] = nil
        flash[:notice] = "ログアウトしました"
        redirect_to("/login")
    end

    def edit
      @user = User.find_by(id: params[:id])
    
    end

    def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    
    
    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
     end
    end

     def destroy
      @user = User.find_by(id: params[:id])
      @user.destroy
      flash[:notice] ="ユーザーを削除しました"
      redirect_to("/users/index")
     end

    def ensure_correct_user
        if @current_user.id != params[:id].to_i
          flash[:notice] = "権限がありません"
          redirect_to articles_path
        end
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>

  <%= link_to("トップページへ戻る","/articles")%>
<% end %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
  
<%= link_to("return TOP","/articles")%>
<% end %>


app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to("トップページへ戻る","/articles")%>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    </head>
<body>
 <header>
 <ul class="header-menus">
 <% if @current_user %>
 <li>
   <%= link_to(@current_user.name, "/users/#{@current_user.id}") %>
 </li>
   <li>
   <%= link_to("logout","/logout", {method: :post}) %>

 </li>
 <li>
 <%= link_to("TOP","/articles")%>

</li>
<li>
 <%= link_to("new article","/articles/new")%>

</li>
<li>
 <%= link_to("MENBERS","/users/index")%>

</li>
<% else %>
 <li>
 <%= link_to("login","/login") %>
 </li>
<li>
 <%= link_to("signup","/signup")%>
 </li>
<% end %>
</ul>
</header>
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    
  </body>
</html>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">MENBERS</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
         
        </div>
        <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main_user">
 <div class="container">
 <div class="form-heading">login</div>
  <div class="users_form">
  <div class="form_body">
  <% if @error_message %>
  <div class="form-error">
    <%= @error_message %>
  </div>
  <% end %>
  <%= form_tag("/login") do %>
   <p>name</p>
   <input name="name" value="<%= @name %>">
   <p>password</p>
   <input type="password" name="password" value="<%= @password %>">
  <input type="submit" value="login">
  <% end %>
    </div>
   </div>
  </div>
  </div>

 

app/views/users/new.html.erb

<div class="users-new">
    <div class="container">
        <div class="form-heading">signup form</div>
        <div class="users-form">
            <div class="form-body">
                <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_tag("/users/create") do %>
                <p>name</p>
                <input name="name" value="<%= @user.name %>">
                <p>password</p>
                <input type="password" name="password" value="<%= @user.password %>">
                <input type="submit" value="signup">
            <% end %>
            </div>
        </div>
    </div>
</div>